import = ["~/.config/alacritty/kanagawa_wave.toml"]
live_config_reload = true

[cursor]
blink_interval = 550
blink_timeout = 0
thickness = 0.2
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15.5

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 1
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
dynamic_padding = false
dynamic_title = false
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Windowed"

[window.dimensions]
columns = 160
lines = 40

[window.padding]
x = 6
y = 6
